### PR TITLE
Support rar

### PR DESCRIPTION
**Pull request by op**
This PR depends on #7 because they both touch the same line. :)

### CODE REVIEW

**Comment by yuhonas** [comment]
Alright so I started taking a look at this and it's a bit of a rabbit hole

1. unraring sounds totally reasonable, awesome spot! I didn't notice `rar` files on [artscene.textfiles.com](http://artscene.textfiles.com/) but then I asked the question what other archive format's should we support? is it just zip/rar, is `ansi_art_download` to be used elsewhere? are we building a zsh plugin or a bulk ansi art downloader/unpacker/thing
2. `rar` is a proprietary format (as you rightly mentioned in your PR) and I wasn't able to find `unrar` cross platform through [homebrew](https://github.com/orgs/Homebrew/discussions/285) so the `$+commands[unrar]` check won't work on mac (which I use)
3. I tried searching for a multi-platform unarchiver that supports `rar` and found [7zip](https://7-zip.org/) which would handle both zip & rar but despite preaching it has `rar` support I ran into [some issues](https://github.com/orgs/Homebrew/discussions/3355) at least with the `rar`s on artscene

After that I started to rethink this whole approach on why we're even jumping through all these hoops preprocessing these archives for display (downloading, unpacking multiple zip formats, dealing with inconsistent filename extension casing eg `ANS` vs `ans`) then came to the conclusion it might just be better to mirror [artscene.textfiles.com](http://artscene.textfiles.com/) (which doesn't change) with a clean version that has all these nuances rectified so the logic on this side would be drastically simpler, we could then also have ANSI previews like [16colo.rs](https://16colo.rs/)

I'm looking into it but I think it would be pretty cool and simplify thing's greatly

[edit] I just discovered [16colo.rs](https://16colo.rs/) has rsync/ftp which you can access the raw ansi so we could just switch to using them as an ansi art source eg to download all ansi art from 1994 from 16colors

```
rsync -azvhP --include '*/' --include '*.ANS' --exclude '*' rsync://16colo.rs/pack/1994 $ANSI_MOTD_ART_DIR
```

**Comment by op** [comment]
Sounds cool!

FYI: the package in brew seem to be called `rar`. In Debian based systems, it's `unrar`. In Arch, either works.
https://formulae.brew.sh/cask/rar

**Comment by yuhonas** [comment]
Yeah I tried that brew package and `unrar` gave me this sadly!
image

**Comment by op** [comment]
OK, screw `rar`. :)

**Pull request closed without merging**
